# Generated by Django 5.2.3 on 2025-07-01 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0002_singer_created_at_singer_updated_at_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='singer.singer'),
        ),
    ]
